Traceback (most recent call last):
  File "/gpfs/fs001/cbica/projects/RBC/QC_Concatenation/HBN_CPAC/generate_CPAC_QC.py", line 22, in <module>
    df["medianFD"]=(pd.DataFrame.median(pd.read_table(median_file[0])))[0]
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1242, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/cbica/projects/RBC/QC_Concatenation/HBN_CPAC/cpac_RBCv0/sub-NDARRT038VG1/ses-HBNsiteRU/func/sub-NDARRT038VG1_ses-HBNsiteRU_task-movieDM_desc-FDJenkinson_motion.1D'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/fs001/cbica/projects/RBC/QC_Concatenation/HBN_CPAC/generate_CPAC_QC.py", line 25, in <module>
    df["medianFD"]=(pd.DataFrame.median(pd.read_table(median_file[0])))[0]
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1242, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/cbica/projects/RBC/miniconda3/lib/python3.10/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/cbica/projects/RBC/QC_Concatenation/HBN_CPAC/cpac_RBCv0/sub-NDARRT038VG1/ses-HBNsiteRU/func/sub-NDARRT038VG1_ses-HBNsiteRU_task-movieDM_desc-FDJenkinson_motion.1D'
